# Generated by Django 6.1.1 on 2026-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('display_name', models.CharField(blank=True, max_length=512)),
                ('provider', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'geocode cache entries',
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=5, max_digits=7)),
                ('geocode_source', models.CharField(default='census', max_length=16)),
            ],
            options={
                'ordering': ('state', 'city', 'name'),
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routeplanne_latitud_378953_idx')],
            },
        ),
    ]
